name: Test and Deploy SAM App

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - 'template*.yaml'
      - 'template*.yml'
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  test:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Debug file location
        run: ls -R

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

  deploy:
    name: Package and Deploy SAM
    runs-on: ubuntu-latest
    needs: test  # Only run if tests pass

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'eu-north-1' }}

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Package SAM application
        env:
          SAM_CLI_TELEMETRY: 0  # disables SAM telemetry
        run: |
          sam package \
            --template-file template.yaml \
            --output-template-file packaged.yaml \
            --s3-bucket cloud-resume-challenge-petterr-n \
            --no-resolve-s3

      - name: Deploy SAM application
        env:
          SAM_CLI_TELEMETRY: 0
        run: |
          sam deploy \
            --template-file packaged.yaml \
            --stack-name resume-app-stack \
            --capabilities CAPABILITY_IAM \
            --no-resolve-s3
        continue-on-error: true